name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install_lcov
      run: sudo apt-get install -y lcov
    - name: tests
      run: bash scripts/run_tests.sh 
