name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install_glut
      run: sudo apt-get install freeglut3-dev
    - name: tests
      run: bash scripts/run_tests.sh 
